{{- if and .Values.web.enabled .Values.web.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-app.fullname" . }}-web
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "laravel-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
{{- end }}
